openapi: 3.0.0
info:
  title: API de Pessoas
  version: "1.0"
paths:
  /pessoas:
    get:
      operationId: app.routes.pessoas_routes.listar_pessoas
      responses:
        200:
          description: Lista de pessoas
    post:
      operationId: app.routes.pessoas_routes.criar_pessoa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pessoa"
      responses:
        201:
          description: Pessoa criada
  /pessoas/{id}:
    get:
      operationId: app.routes.pessoas_routes.obter_pessoa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Pessoa encontrada
    put:
      operationId: app.routes.pessoas_routes.atualizar_pessoa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pessoa"
    delete:
      operationId: app.routes.pessoas_routes.deletar_pessoa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
components:
  schemas:
    Pessoa:
      type: object
      properties:
        nome:
          type: string
        sobrenome:
          type: string
