openapi: 3.0.0
info:
  title: "People API"
  description: "An API to manage people registers"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    PersonSchema:
      type: "object"
      required:
        - full_name
        - age
        - phone_number
      properties:
        full_name:
          type: "string"
        phone_number:
          type: "list"
        age:
          type: "integer"
  parameters:
    full_name:
      name: "full_name"
      description: "The person full name"
      in: path
      required: True
      schema:
        type: "string"
    phone_number:
      name: "phone_number"
      description: "List of phone number"
      in: path
      required: true
      schema:
        type: "list"
    age:
      name: "age"
      description: "Person age"
      in: path
      required: true
      schema:
        type: "integer"

paths:
  /people:
    get:
      operationId: app.routes.people_routes.list_people
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        200:
          description: Lista de pessoas.
        404:
          description: Não pessoas cadastradas.
    post:
      operationId: app.routes.people_routes.create_person
      tags:
        - "People"
      summary: "Creates a person"
      requestBody:
        description: "Person to create"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PersonSchema"
      responses:
        "201":
          description: "Successfully created person"

  /people/{full_name}:
    get:
      operationId: app.routes.people_routes.read_person
      tags:
        - "People"
      summary: "Read one person by Full Name"
      responses:
        200:
          description: Pessoa encontrada com sucesso.
        404:
          description: Pessoa não encontrada.
      parameters:
        - name: full_name
          in: path
          required: true
          schema:
            type: string
        
    
  #   post:
  #     operationId: app.routes.pessoas_routes.criar_pessoa
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: "#/components/schemas/Pessoa"
  #     responses:
  #       201:
  #         description: Pessoa criada
  # /pessoas/{id}:
  #   get:
  #     operationId: app.routes.pessoas_routes.obter_pessoa
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       200:
  #         description: Pessoa encontrada
  #   put:
  #     operationId: app.routes.pessoas_routes.atualizar_pessoa
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: "#/components/schemas/Pessoa"
  #   delete:
  #     operationId: app.routes.pessoas_routes.deletar_pessoa
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         schema:
  #           type: string
components:
  schemas:
    Pessoa:
      type: object
      properties:
        nome:
          type: string
        sobrenome:
          type: string
