openapi: 3.0.0
info:
  title: "People API"
  description: "An API to manage people registers"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /people:
    get:
      operationId: app.routes.people_routes.list_people
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        200:
          description: Lista de pessoas.
        404:
          description: Não pessoas cadastradas.
  /people/{full_name}:
    get:
      operationId: app.routes.people_routes.read_person
      tags:
        - "People"
      summary: "Read one person by Full Name"
      responses:
        200:
          description: Pessoa encontrada com sucesso.
        404:
          description: Pessoa não encontrada.
      parameters:
        - name: full_name
          in: path
          required: true
          schema:
            type: string
        
    
  #   post:
  #     operationId: app.routes.pessoas_routes.criar_pessoa
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: "#/components/schemas/Pessoa"
  #     responses:
  #       201:
  #         description: Pessoa criada
  # /pessoas/{id}:
  #   get:
  #     operationId: app.routes.pessoas_routes.obter_pessoa
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       200:
  #         description: Pessoa encontrada
  #   put:
  #     operationId: app.routes.pessoas_routes.atualizar_pessoa
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         schema:
  #           type: string
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: "#/components/schemas/Pessoa"
  #   delete:
  #     operationId: app.routes.pessoas_routes.deletar_pessoa
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         schema:
  #           type: string
components:
  schemas:
    Pessoa:
      type: object
      properties:
        nome:
          type: string
        sobrenome:
          type: string
