openapi: 3.0.0
info:
  title: People API
  description: An API to manage people registers
  version: 1.0.0

servers:
  - url: /api

components:
  schemas:
    Person:
      type: object
      properties:
        full_name:
          type: "string"
        age:
          type: "integer"
        phone_number:
          type: "array"
          items: 
            type: "string"
      required:
        - full_name
        - age
        - phone_number
  parameters:
    full_name:
      name: full_name
      description: The person full name
      in: query
      required: True
      schema:
        type: string
    age:
      name: age
      description: Person age
      in: query
      required: true
      schema:
        type: integer
    phone_number:
      name: phone_number
      description: List of phone number
      in: query
      required: true
      schema:
        type: array
        items:
          type: string

paths:
  /people:
    get:
      operationId: app.routes.people_routes.list_people
      tags:
        - People
      summary: Read the list of people
      responses:
        200:
          description: Lista de pessoas.
        404:
          description: Não há pessoas cadastradas.
    post:
      operationId: app.routes.people_routes.create_person
      tags:
        - People
      summary: Creates a person
      requestBody:
        description: Person to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        201:
          description: "Successfully created person"
        200:
          description: "Request OK"
        401:
          description: "This person was created before!"

  /people/{full_name}:
    get:
      operationId: app.routes.people_routes.read_person
      tags:
        - People
      summary: Read one person by Full Name
      responses:
        200:
          description: Pessoa encontrada com sucesso.
        404:
          description: Pessoa não encontrada.
      parameters:
        - name: full_name
          in: path
          required: true
          schema:
            type: string
    put:
      operationId: app.routes.people_routes.update_person
      tags:
      - People
      parameters:
        - name: full_name
          in: query
          required: true
          schema:
            type: string
          description: "Name to be updated"
      requestBody:
        content:
          application/json:
            schema:
                type: object
                properties:
                  full_name:
                    type: "string"
            # parameters:
            #   full_name:
            #     name: full_name
            #     description: The person full name
            #     in: query
            #     required: True
            #     schema:
            #       type: string
            #   age:
            #     name: age
            #     description: Person age
            #     in: query
            #     required: true
            #     schema:
            #       type: integer
            #   phone_number:
            #     name: phone_number
            #     description: List of phone number
            #     in: query
            #     required: true
            #     schema:
            #       type: array
            #       items:
            #         type: string
      responses:
        200:
          description: "Pessoa atualizada com sucesso!"
        404:
          description: "Pesso não encontrada!"
    # delete:
    #   operationId: app.routes.pessoas_routes.deletar_pessoa
    #   parameters:
    #     - name: id
    #       in: path
    #       required: true
    #       schema:
    #         type: string

