name: Deploy para Render

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar dependências
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - run: |
        pip install -r requirements.txt
        pip install pytest

    # - name: Rodar testes
    #   run: pytest

    - name: Disparar deploy no Render
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
